# Please note that emoji usages follows this guide: https://gitmoji.dev/
---
name-template: '$RESOLVED_VERSION 🌈'
tag-template: '$RESOLVED_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS

categories:
  - title: '✨ New Features/ Enhancements'
    labels:
      - 'feature'
      - 'enhancement'
      - 'feat'
      - 'improvement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '📝 Documentation'
    labels:
      - 'documentation'
      - 'doc'
      - 'docs'
  - title: '🧩 Dependencies'
    labels:
      - 'dependencies'
      - 'dependency'
  - title: '💚 Chores'
    labels:
      - 'chores'
      - 'chore'
exclude-labels:
  - 'skip-changelog'
version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
      - 'feat'
      - 'improvement'
      - 'dependencies'
      - 'dependency'
  patch:
    labels:
      - 'documentation'
      - 'doc'
      - 'docs'
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'chore'
      - 'chores'
  default: patch
...
